name: to_do_app_v1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.17.0
  path_provider: ^2.0.11
  sizer: ^2.0.15
  sqflite: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/TODO.png"
  generate: true

flutter:

  uses-material-design: true

  assets:
    - asset/images/TODO.png

